[mobile] make sshd feature optional and related navigation refactoring
calamares/calamares-branding pull request #6
Opened 2020-12-09 14:46 UTC by ollieparanoid

Some distributions need the sshd feature disabled for now, so make it optional. Refactor the navigation code so we won't get into trouble when making other (possibly new) features optional, too. See commit messages for details.

2020-12-17 12:27 UTC, adriaandegroot approved these changes

2020-12-17 12:27 UTC, adriaandegroot commented on modules/mobile/Config.cpp
> +cfgBool( const QVariantMap& cfgMap, QString key, bool defaultBool )
From utils/variant.h:

```
/**
 * Get a bool value from a mapping with a given key; returns @p d if no value.
 */
DLLEXPORT bool getBool( const QVariantMap& map, const QString& key, bool d = false );
```

You should be able to use that instead (this just seems like unnecessary code duplication)

2020-12-17 12:27 UTC, adriaandegroot commented on modules/mobile/Config.cpp
> +cfgBool( const QVariantMap& cfgMap, QString key, bool defaultBool )
(Also makes me think that `cfgStr()` is probably `CalamaresUtils::getString()` )

2020-12-17 12:27 UTC, adriaandegroot commented on modules/mobile/MobileQmlViewStep.cpp
> +                          m_config->cmdPasswd(),
This is a slightly weird construction that we're trying to drop from other view modules: why does the view module build its jobs *in the view module*, and, weirder still, *when leaving the page*? Most other modules are moving this to a `createJobs()` function in the Config object, which is called by the `jobs()` function of the ViewModule if needed.

But .. not directly related to your PR.

2020-12-17 12:27 UTC, adriaandegroot commented on modules/mobile/UsersJob.h
> +              QString cmdPasswd,
Idiomatic is `const QString&`, but that should have been spotted previously.

2020-12-17 12:27 UTC, adriaandegroot commented on modules/mobile/UsersJob.h
> +    bool m_featureSshd;
Idiomatic -- well, in C++ code that cares for memory size, which we dont -- would be to sort things by size, putting like-sized things together for optimal packing. You might consider a C++17 style initializer here, too, for completeness (e.g. `bool m_featureSshd = true;`)

2020-12-17 12:27 UTC, adriaandegroot commented on modules/mobile/mobile.qml
> +        console.log("Navigating to screen: " + name);
Misplaced debugging? Should we introduce something for QML to explicitly log to the Calamares log file?

2020-12-17 12:27 UTC, merged

2020-12-17 12:28 UTC, adriaandegroot commented
Merged, but you can tell from the comments there's a bunch of things that can be done to tighten up the C++ code. They're not **necessary**, but good future cleanup.

2020-12-17 13:41 UTC, ollieparanoid commented on modules/mobile/mobile.qml
> +        console.log("Navigating to screen: " + name);
No, that's on purpose. My follow up PR will introduce a few more log calls, so maybe the explicit log to calamares log file makes sense. The `console.log` messages are printed in the log file currently (but you can't control the verbosity, which is probably why you suggested to introduce a new thing).

2020-12-18 20:36 UTC, ollieparanoid commented on modules/mobile/UsersJob.h
> +    bool m_featureSshd;
Thanks for the suggestion! I'll leave the `= true` default out though, because then it would be defined in yet another place. It is already in two places, the config and Config.cpp, where `m_*` gets filled from the config.

I've applied your other suggestions though, will make a follow-up PR soon.

2023-04-09 21:07 UTC, ImOdd approved these changes
Top notch.  Thank you

2023-07-29 03:34 UTC, BrianAllen229 requested changes
- [ ]