[mobile] Allow user to configure filesystem type
calamares/calamares-branding pull request #8
Opened 2021-01-04 11:01 UTC by Undef-a

The user can now configure the target root filesystem type. Options
provided are ext4 (default), f2fs and btrfs.

OS Maintainers are required to provide their own BTRFS install script
which configures default submodules as desired.

2021-01-04 18:13 UTC, ollieparanoid requested changes
Thanks for making the PR, @Undef-a. This is a pretty useful feature!

Here goes my review.

2021-01-04 18:13 UTC, ollieparanoid commented on modules/mobile/Config.h
> +    QString m_fstype = "ext4";
Let's make the default filesystem configurable (default `ext4` makes sense).

To add config options:
* add it to mobile.conf
* add it to Config.h
* add it to [Config::SetConfigurationMap](https://github.com/calamares/calamares-extensions/blob/a53f9359f42b6c301b19060f90a5d4e8bc771977/modules/mobile/Config.cpp#L18)

Example: https://github.com/calamares/calamares-extensions/commit/7f750cb1450f133c6bc505e60192804b46ff594d

---

For the fstype option in particular, it also makes sense to turn this into an enum. @adriaandegroot wrote:
> see NamedEnum.h

(I haven't used this myself yet.)

2021-01-04 18:13 UTC, ollieparanoid commented on modules/mobile/PartitionJob.cpp
> +	} );
(Tabs and spaces mixed. Please make use of `.clang-format` in the git repo to automatically format your code.)

2021-01-04 18:13 UTC, ollieparanoid commented on modules/mobile/PartitionJob.cpp
> +    QString devNoPart = dev.chopped(2);
We can't always chop off two characters to go from partition to the device with the partition. When I [run this in QEMU](https://wiki.postmarketos.org/wiki/On-device_installer#Running_in_QEMU), `dev` may be `/dev/vda2` for example. (opposed to `/dev/mmcblk0p2` etc, where there is always a `p` character).

But before changing this, please explain why it is needed at all. Below you are creating an additional ext4 partition. Is this an unrelated change that made it into the patch?

2021-01-04 18:13 UTC, ollieparanoid commented on modules/mobile/PartitionJob.cpp
> +    }
Instead of assuming that cmdMkfsRoot has `@@FSTYPE@@` and replacing that, and replacing `-L` with `-l` in the f2fs case, let's add separate config options for each filesystem type.

Please create a separate commit, which renames `cmdMkfsRoot` to `cmdMkfsRootExt4`. Then add `cmdMkfsBtrfs` and `cmdMkfsF2fs` in your patch and use it here.

(Not many distros have adopted the mobile module yet, so in my opinion we can just rename `cmdMkfsRoot` to `cmdMkfsRootExt4`, without providing backwards compatibility.)

2021-01-04 18:13 UTC, ollieparanoid commented on modules/mobile/mobile.qml
> +		 "screens": ["fs_selection"]},
tabs used instead of spaces

2021-01-04 18:13 UTC, ollieparanoid commented on modules/mobile/mobile.qrc
> +  <file>fs_selection.qml</file> <!-- filesystem selection -->
`fs_selection.qml` is missing from the PR?

2021-01-04 18:13 UTC, ollieparanoid commented on modules/mobile/mobile.qml
> +		{"name": "fstype",
Please add a `featureFstype` config option, so distributions can choose to disable this feature (again, see 7f750cb1450f133c6bc505e60192804b46ff594d).

I would set it to `false` by default, so there are less paths to test when using the `mobile` module with a new Linux distribution.

2021-01-04 18:13 UTC, ollieparanoid commented on modules/mobile/PartitionJob.cpp
> +		m_cmdMkfsRoot.replace(QString("@@FSTYPE@@"), QString("btrfs-installer"));
From the commit message:
> OS Maintainers are required to provide their own BTRFS install script
> which configures default submodules as required.

As written in the other comment, I'd put the btrfs command into `cmdMkfsRootBtrfs`. I'd put `mkfs.btrfs` there by default in the calamares-extensions.git repository.

The installer OS could configure the submodules then either by changing this to a `btrfs-installer` script, or by configuring the submodules in a `shellprocess` install step (call a script that checks if the target partition is btrfs, and if so, configure the modules). You can mention something along these lines in the description of the `cmdMkfsRootBtrfs` option in `mobile.conf`.

2021-01-04 20:40 UTC, Undef-a commented on modules/mobile/PartitionJob.cpp
> +    QString devNoPart = dev.chopped(2);
You are correct. This was a mobian specific change. I'll remove it.

2021-01-04 20:45 UTC, Undef-a commented on modules/mobile/mobile.qrc
> +  <file>fs_selection.qml</file> <!-- filesystem selection -->
Yes. I must have missed it trying to remove Mobian specific code. Added now.

2021-01-05 08:20 UTC, Undef-a commented on modules/mobile/Config.h
> +    QString m_fstype = "ext4";
I believe the first half of this is done. However, I'm not sure exactly how to implement NamedEnums for this. Is there an implementation somewhere you could point me to?

2021-01-05 08:21 UTC, Undef-a commented
Thanks for the review @ollieparanoid. Plenty of good points there.

2021-01-08 02:23 UTC, ollieparanoid requested changes

2021-01-08 02:23 UTC, ollieparanoid commented on modules/mobile/Config.cpp
> +    m_cmdMkfsRootBtrfs = getString( cfgMap, "cmdMkfsRootBtrfs", "mkfs.btrfs -L 'unknownOS_root'" );
Please order them alphabetically (btrfs, ext4, f2fs). Here and the several times they were added below.

2021-01-08 02:23 UTC, ollieparanoid commented on modules/mobile/Config.h
> +	Q_PROPERTY( bool featureFstype READ featureFstype CONSTANT FINAL )
Indentation is wrong here, and also several times throughout the file.

Run this on each commit:
```sh
clang-format -i $(find . -regex '.*\.\(c\|cpp\|h\)')
```

(Existing commits need to be squashed into one though, from a quick glance they are all just partially implementing the feature and wouldn't work on their own.)

2021-01-08 02:23 UTC, ollieparanoid commented on modules/mobile/PartitionJob.cpp
> +    if (m_fstype == QString("btrfs")) {
switch ... case seems more suitable here.

2021-01-08 02:23 UTC, ollieparanoid commented on modules/mobile/PartitionJob.cpp
> +
(unrelated new empty lines)

2021-01-08 02:23 UTC, ollieparanoid commented on modules/mobile/fs_selection.qml
> +        id: welcomeText
change to `mainText` (see https://github.com/calamares/calamares-extensions/commit/a6a9dc68902327c51aca47bb3eaa42758d6b2bd0)

2021-01-08 02:23 UTC, ollieparanoid commented on modules/mobile/fs_selection.qml
> +		anchors.top: welcomeText.bottom
`mainText.bottom`

2021-01-08 02:23 UTC, ollieparanoid commented on modules/mobile/Config.h
> +    QString cmdMkfsRootF2fs() const { return m_cmdMkfsRootf2fs; }
```suggestion
    QString cmdMkfsRootF2fs() const { return m_cmdMkfsRootF2fs; }
```

2021-01-08 02:23 UTC, ollieparanoid commented on modules/mobile/mobile.conf
> +## command be a script which will create a subvolume and make it default
Can you add a link here to the script you are using in mobian, for reference?

2021-01-08 02:23 UTC, ollieparanoid commented on modules/mobile/fs_selection.qml
> +        text: qsTr("OK")
Other screens that don't have a selection, have "Continue" as button text.

2021-01-08 02:23 UTC, ollieparanoid commented on modules/mobile/mobile.qml
> +         "screens": ["fs_selection"]},
the title for `fs_selection` needs to be set in `titles` above, right now it says "undefined"

2021-01-08 02:23 UTC, ollieparanoid commented on modules/mobile/Config.h
> +    QString m_fstype = "ext4";
Thanks for adding all the config options!

There is still an option missing to make the default fs type configurable.

> However, I'm not sure exactly how to implement NamedEnums for this. Is there an implementation somewhere you could point me to?

Looking at code in calamares... the welcomeq module from calmares proper has a language selection with a combo box:

* https://github.com/calamares/calamares/blob/132ff59d9c8b20147d3e16112c70998b59b05c69/src/modules/welcomeq/welcomeq.qml#L163-L171
* https://github.com/calamares/calamares/blob/132ff59d9c8b20147d3e16112c70998b59b05c69/src/modules/welcome/Config.cpp#L83-L87
* https://github.com/calamares/calamares/blob/132ff59d9c8b20147d3e16112c70998b59b05c69/src/modules/welcome/Config.h#L119

This uses a LabelModel instead of NamedEnum though, so that's probably the right one to use here.

(@adriaandegroot: or is it?)

2021-01-08 02:23 UTC, ollieparanoid commented on modules/mobile/fs_selection.qml
> +	}
`config.fstype` needs to be selected by default, so:
* the default fstype from the `mobile.conf` is selected first
* when going back to this screen, the previously selected value is still selected. Right now it forgets what was selected if you click OK and then go back. (all other screens show previous input when going back.)


Apparently we need to set `currentIndex` for that, here is an example: https://doc.qt.io/qt-5/qml-qtquick-controls2-combobox.html#combobox-model-roles (note that currentIndex takes an integer).

2021-01-08 02:23 UTC, ollieparanoid commented on modules/mobile/fs_selection.qml
> +        text: "Select filesystem for root partition."
I've tried to word the other screens with casual users in mind, so:

```suggestion
        text: "Select the filesystem for root partition. If unsure, leave the default."
```

(I think the installer would benefit from a screen at the beginning, that asks if the user wants an advanced mode or a simple mode, the simple mode would then hide the ssh question and the filesystem question and whatever power user stuff we add in the future; but that's out of scope for this PR.)

2021-01-08 02:23 UTC, ollieparanoid commented on modules/mobile/mobile.conf
> +# featureFstype: false
as written in the other comment, the default fs type needs to be configurable here.

2021-01-08 03:08 UTC, Undef-a commented on modules/mobile/mobile.conf
> +## command be a script which will create a subvolume and make it default
I can link to the PR, but not the final script which will be merged in after this. It should be changed when the Mobian release is made.

2021-01-08 05:03 UTC, Undef-a commented on modules/mobile/Config.h
> +    QString m_fstype = "ext4";
I've got a partial version of this, but it doesn't compile. 

```
In file included from /home/user/QubesIncoming/phone/calamares-settings-mobian/build/modules/mobile/calamares_viewmodule_mobile_autogen/mocs_compilation.cpp:2:
/home/user/QubesIncoming/phone/calamares-settings-mobian/build/modules/mobile/calamares_viewmodule_mobile_autogen/EWIEGA46WW/moc_Config.cpp: In static member function ‘static void Config::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)’:
/home/user/QubesIncoming/phone/calamares-settings-mobian/build/modules/mobile/calamares_viewmodule_mobile_autogen/EWIEGA46WW/moc_Config.cpp:275:92: error: no match for ‘operator=’ (operand types are ‘CalamaresUtils::Locale::LabelModel’ and ‘CalamaresUtils::Locale::LabelModel*’)
  275 |         case 15: *reinterpret_cast< CalamaresUtils::Locale::LabelModel*>(_v) = _t->fsmodel(); break;
      |                                                                                            ^
In file included from /home/user/QubesIncoming/phone/calamares-settings-mobian/build/modules/mobile/calamares_viewmodule_mobile_autogen/EWIEGA46WW/../../../../../modules/mobile/Config.h:6,
                 from /home/user/QubesIncoming/phone/calamares-settings-mobian/build/modules/mobile/calamares_viewmodule_mobile_autogen/EWIEGA46WW/moc_Config.cpp:10,
                 from /home/user/QubesIncoming/phone/calamares-settings-mobian/build/modules/mobile/calamares_viewmodule_mobile_autogen/mocs_compilation.cpp:2:
/usr/include/libcalamares/locale/LabelModel.h:27:17: note: candidate: ‘CalamaresUtils::Locale::LabelModel& CalamaresUtils::Locale::LabelModel::operator=(const CalamaresUtils::Locale::LabelModel&)’ (deleted)
   27 | class DLLEXPORT LabelModel : public QAbstractListModel
      |                 ^~~~~~~~~~
/usr/include/libcalamares/locale/LabelModel.h:27:17: note:   no known conversion for argument 1 from ‘CalamaresUtils::Locale::LabelModel*’ to ‘const CalamaresUtils::Locale::LabelModel&’
```

2021-01-19 09:11 UTC, Undef-a commented on modules/mobile/Config.h
> +    QString m_fstype = "ext4";
I have now got this working with one exception: Instead of saving the filesystem name into `config.fsType` it saves a locale string in the format `* f2fs (C)`. 

Otherwise, the default is now set on entry and (bug aside) the selected filesystem would be correctly selected if back is pressed.

2021-01-22 02:58 UTC, Undef-a commented
Currently this has a bug which causes the external to internal installer to be invoked when not configured.

2021-01-24 07:41 UTC, ollieparanoid requested changes
Great work, @Undef-a! You even figured out how to get the combobox entries dynamically generated and how to make it properly display the previous selection when using the back button. :tada: 

I've tried your patch and it works as expected.

I think this is almost ready to merge now, review is mostly consistency nitpicks.

2021-01-24 07:41 UTC, ollieparanoid commented on modules/mobile/Config.cpp
> +    m_fsmodel = getString( cfgMap, "fsmodel", "ext4,f2fs,btrfs" );
For consistency: `fsModel` instead of `fsmodel` (throughout whole patch)

2021-01-24 07:41 UTC, ollieparanoid commented on modules/mobile/Config.cpp
> +    /* Locale::Label l_defaultLocale = new Locale::Label( m_defaultFs, Locale::Label::LabelFormat::IfNeededWithCountry, m_fsLabelModel ); */
This line of commented out code looks like a left-over. Remove it?

(Are you working on a patch for locale support too? Or was this used as template from some calamares code?)

2021-01-24 07:41 UTC, ollieparanoid commented on modules/mobile/Config.cpp
> +Config::setFsType( const QString& fstype )
`fstype` -> `fsType` (throughout the whole patch)

2021-01-24 07:41 UTC, ollieparanoid commented on modules/mobile/Config.h
> +    bool featureFstype() { return m_featureFstype; };
`featureFsType`

2021-01-24 07:41 UTC, ollieparanoid commented on modules/mobile/Config.h
> +    QString m_fsmodel = "ext4,f2fs,btrfs";
I suggest we put the default values in `setConfigurationMap()` instead of duplicating them here, because:

* One less place to adjust if we want to change the default.
* Consistency with the other config options above.

Therefore I'd remove the default string from `m_fsmodel` and `m_defaultFs`.

2021-01-24 07:41 UTC, ollieparanoid commented on modules/mobile/PartitionJob.cpp
> +    else
To prevent unintended behaviour, let's explicitly check for ext4 here, and throw an error if the fstype is anything else (see ` return JobResult::error` below).

2021-01-24 07:41 UTC, ollieparanoid commented on modules/mobile/PartitionJob.cpp
> +    QString m_cmdMkfsRoot = m_cmdMkfsRootExt4;
Whatever we set here is overwritten below, so let's change this to `QString m_cmdMkfsRoot;`.

2021-01-24 07:41 UTC, ollieparanoid commented on modules/mobile/mobile.conf
> +# defaultFs: ext4
```suggestion
## Ask the user, which filesystem to use.
# featureFsType: false
## Filesystems that the user can choose from.
# fsModel: ext4,f2fs,btrfs
## Default filesystem to display in the dialog. If featureFsType is disabled,
## this gets used without asking the user.
# defaultFs: ext4
```

changes:
* explained each option.
* explicitly wrote that defaultFs gets used even if featureFsType is false, as this might not be obvious.
* changed featureFstype -> featureFsType and fsmodel -> fsModel (see other comments).

2021-01-24 07:41 UTC, ollieparanoid commented on modules/mobile/mobile.conf
> +## command be a script which will create a subvolume and make it default
Thanks, this is very useful!

2021-01-24 07:41 UTC, ollieparanoid commented on modules/mobile/mobile.conf
> +#
I suggest to remove this line, and start the btrfs related comment above with `Btrfs: to allow snapshots...`.

2021-01-24 07:41 UTC, ollieparanoid commented on modules/mobile/mobile.conf
> -# cmdMkfsRoot: "mkfs.ext4 -L 'unknownOS_root'"
Can you mention in https://github.com/calamares/calamares-extensions/blob/calamares/CHANGES, that `cmdMkfsRoot` was renamed to `cmdMkfsRootExt4`?

2021-01-24 07:41 UTC, ollieparanoid commented on modules/mobile/fs_selection.qml
> +        /* Label we are searching for is of the format "* ext4 (C)" */
`* ext4 (C)` looks pretty weird in the UI.

@adriaandegroot: can you give a hint how we could set a label text?

(If this is much effort, I suggest to do that in a future PR and rather get this one merged soon.)

2021-01-26 10:24 UTC, Undef-a commented on modules/mobile/Config.cpp
> +    /* Locale::Label l_defaultLocale = new Locale::Label( m_defaultFs, Locale::Label::LabelFormat::IfNeededWithCountry, m_fsLabelModel ); */
That was just a left over from trying to work out the Locale bit of the LabelModel. It'll be gone shortly.

2021-01-26 10:49 UTC, Undef-a commented
> cannot reproduce. If `targetDeviceRootInternal` is not in `mobile.conf`, the feature will be skipped (see [`skipFeatureInstallTarget()`](https://github.com/calamares/calamares-extensions/blob/a53f9359f42b6c301b19060f90a5d4e8bc771977/modules/mobile/mobile.qml#L150-L152)). I just tried it out and it got skipped as expected:

That comment was made as a not for my on testing. It seemed to happen a few times when I was recently trying to flash my phone. If it's not reproducible, its probably related to the semi-finished Mobian packaging I was using.

2021-02-01 15:45 UTC, ollieparanoid commented
Looks good to me! :+1: Thanks again for all the work you've put into this, @Undef-a!

@adriaandegroot: can you please take a look at this?

If you think it's ready to merge, it would be great to merge #10 as well and tag a new release.

2021-02-04 10:05 UTC, adriaandegroot commented on modules/mobile/Config.h
> +    CalamaresUtils::Locale::LabelModel* fsModel() const;
This is a really peculiar choice. `Locale::LabelModel` is a model containing names of locales: it offers current-language and native-language names for locales (e.g. "Dutch" and "Nederlands"). If a locale is unknown to Qt (e.g. Esperanto, before Qt 5.12) then an additional "(C)" is added, indicating that Calamares is going to treat this as C locale (e.g. no translations, no locale support).

I suppose you **can** stick a handful of strings in it, but it does not seem like a good fit. For what it's worth, KPMCore offers a list of (translated) filesystem names.

2021-02-04 10:05 UTC, adriaandegroot commented on modules/mobile/Config.h
> +    void setFsType( const int idx );
`int` is a value type, there's not much point in making it `const` (but that's C++-stylistic nitpicking)

2021-02-04 10:05 UTC, adriaandegroot commented on modules/mobile/Config.h
> +    Q_PROPERTY( QString cmdMkfsRootF2fs READ cmdMkfsRootF2fs CONSTANT FINAL )
Do these really need to be exposed as properties? Seems like an internal thing to me (so was the previous `cmdMkfsRoot`). Unless you're expecting these to be displayed or edited from QML, it's better to hide them.

2021-02-04 10:05 UTC, adriaandegroot commented on modules/mobile/Config.h
> +    CalamaresUtils::Locale::LabelModel* m_fsLabelModel;
See above -- LabelModel is intended to store names of locales (and their translations), not arbitrary string lists. It's a lousy name, I'll give you that (and there's no documentation for that class).

2021-02-04 10:05 UTC, adriaandegroot commented on modules/mobile/PartitionJob.cpp
> +    QString m_cmdMkfsRoot;
Generally in Calamares code, we use `m_` as a prefix for member variables; this is just a local variable, so it's weird to see it named like that.

2021-02-04 10:05 UTC, adriaandegroot commented on modules/mobile/PartitionJob.cpp
> +    , m_fsType( fsType )
Can `m_fsType` change after the Job is created? If not, why not pass the appropriate command in the constructor (along with the type, for whatever reasons) and leave the logic of picking the right command to the caller / creator of the job?

2021-02-04 10:05 UTC, adriaandegroot commented on modules/mobile/fs_selection.qml
> +        /* Label we are searching for is of the format "* ext4 (C)" */
Use a model for string lists, rather than one for selecting locales; even better is probably writing a model (it would go in `libcalamares/partition/FileSystem.h` most likely) that shows a handful of filesystem names / types.

2021-02-04 10:05 UTC, adriaandegroot commented on modules/mobile/mobile.conf
> +# fsModel: ext4,f2fs,btrfs
If you really, specifically, explicitly want to use comma-separated identifiers here, you should document that. Otherwise it's probably nicer (although it doesn't save any code elsewhere) to specify this as a YAML list.

2021-02-04 10:09 UTC, adriaandegroot commented
Lots of comments, but the decision is down to you: if it works for your use-case and gives you the UI you want, then it's fine.

2021-02-08 21:26 UTC, ollieparanoid commented
Thanks a lot for the thorough review! I think these review points should be addressed before we merge it.

> Use a model for string lists, rather than one for selecting locales; even better is probably writing a model (it would go in libcalamares/partition/FileSystem.h most likely) that shows a handful of filesystem names / types.

Getting the file system selection right seems like the most complex part... @adriaandegroot, can you write a draft of how the addition to FileSystem.h should look like?

2021-02-16 09:53 UTC, Undef-a commented
I think all of the above are now resolved, thanks for the through review. I need to build/flash a test image of this on an actual phone, but pending that I believe this is ready for another review.

2021-02-16 11:32 UTC, adriaandegroot approved these changes

2021-02-16 11:32 UTC, adriaandegroot commented on modules/mobile/Config.cpp
> +    m_cmdMkfsRootBtrfs = getString( cfgMap, "cmdMkfsRootBtrfs", "mkfs.btrfs -L 'unknownOS_root'" );
Are distro's expected to set the configuration values (in `mobile.conf`) in order to change the FS label? Perhaps it would be useful to define some substitutions and then use KMacroExpander .. but that's for another iteration of this module, let's get this in first.

Suggested substitutions:
- *fslabel*, defined in the configuration file for this module
- *shortname*, which is the branding-defined short name of the distro
- *root*, which expands to .. "root" I guess

Then the make-fs commands could be defined as `mkfs.ext4 -L '${fslabel}'`, for instance, and if a distro wants to change that, only changing *fslabel* in the config file (once!) is needed, rather than updating three commands.

But: future work

2021-02-16 11:32 UTC, adriaandegroot commented on modules/mobile/Config.cpp
> +    }
I'm not *really* thrilled with string comparisons like this, since it gives opportunities for typo's and other things that are caught at runtime, rather than compile-time. I don't immediately see how to improve this, though, since introducing an enum becomes complicated with the QML parts that use a string list for display (or you'd have to move to a more expressive model).

2021-02-16 11:32 UTC, adriaandegroot commented on modules/mobile/Config.cpp
> +        v->onInstallationFailed( "Unknown filesystem: '" + m_fsType + "'", "");
Clever! This is needed, of course, since you're running jobs here which kind of goes against the grain of how Calamares is designed, but it **does** let you report failure effectively.

Note that you're missing a `tr()` call here, so it is not going to be translated (but, come to that, translations of calamares-extensions are not available at all).

2021-02-16 11:32 UTC, adriaandegroot commented on modules/mobile/Config.cpp
> +                                          m_fdePassword);
Calamares coding style says "put that space there", but that's an easy fix with the styling-tool.

2021-02-16 11:32 UTC, adriaandegroot commented on modules/mobile/Config.h
> +    QStringList fsList() const;
Why is this getter not inline? It doesn't matter much, but it would be stylistically consistent to also `{return m_fsList; }` here, and not have the out-of-line definition in `Config.cpp`.

2021-02-16 11:32 UTC, adriaandegroot commented on modules/mobile/Config.cpp
> +    m_fsType = m_fsList[ idx ];
This body could be squashed down to `setFsType( m_fsList[ idx ] );` .. doesn't save much, but gives you **one** place to check for validity and emit related signals.

2021-02-16 11:32 UTC, adriaandegroot commented on modules/mobile/Config.cpp
> +    m_fsType = m_fsList[ idx ];
Do you think bounds-checking `idx` is needed? It seems slightly hazardous so accept any int here; if the QML code is changed (I dunno, let's set the type to -1 while we don't know what to use) then things will go very wrong here.

2021-02-16 11:32 UTC, adriaandegroot commented on modules/mobile/Config.cpp
> +    m_fsType = fsType;
Often setters will check if the change is actually a change, to avoid sending useless signals (e.g. add a `if (fsType != m_fsType)` block)

2021-02-16 11:32 UTC, adriaandegroot commented on modules/mobile/Config.h
> +    int m_fsIndex;
What is the index for? It looks like "just a number" and I don't see it being used. Maybe some documentation in the `Config.h` header -- say on the getters for these properties -- would help.

2021-02-16 11:35 UTC, adriaandegroot commented
So, I'm going to try to set up CI for calamares-extensions first, then merge this, then apply coding-style and minor tweaks to the code. The comments I have just made in the review are "this would be a neat extra feature" kind of things, and trivia like coding-style. Overall it looks pretty solid and warrants a new release of calamares-extensions.

2021-02-17 10:13 UTC, adriaandegroot commented
@Undef-a CI is now set up, just give me (or @ollieparanoid , who can then ping me on IRC) a sign if you think it can be merged; I don't want to do that if you're still working on this branch because it would mess up your workflow.

2021-02-17 10:46 UTC, Undef-a commented
After that squash and last config change I'm pretty happy with it, and I can work on the polish you brought up in another branch. Just writing an image to test it on a real device now. 

I'll yell out in #calamares when that is done.

2021-02-17 12:07 UTC, Undef-a commented
My testing is triggering the internal from external installer again. This is using the mobian packaging, which currently does not have any logic for this function. 

It also happens on the stock mobile.conf from this PR. 

Until I can work out why this is happening, this probably should not be merged.

2021-02-17 14:38 UTC, ollieparanoid commented
@Undef-a: weird, I'll ping you in IRC so we can work this out.

2021-02-18 00:03 UTC, Undef-a commented
Successfully tested on device. Lucky I did as there were two blocking bugs:

- I changed the order of arguments in PartitionJob. 
- External -> internal install was triggered. 

@ollieparanoid Thanks for the help with these. Could you please review the fix for the external -> internal issue. I believe that when the option is not triggered, this was defaulting to "true" on Mobian, resulting in the error. I have initialized this variable to fix it, which solved the issue, but I can't confirm that it won't cause you issues.

2021-02-21 18:46 UTC, ollieparanoid approved these changes
> Could you please review the fix for the external -> internal issue. I believe that when the option is not triggered, this was defaulting to "true" on Mobian, resulting in the error. I have initialized this variable to fix it, which solved the issue, but I can't confirm that it won't cause you issues.
> 
> EDIT: Specifically referring to L159 of Config.h

Tested with your branch with both installing to internal and external storage with QEMU, and it still works as expected. Moreover you found and fixed a real bug there, the variable was uninitialized and I didn't notice.

This PR is ready to merge in my opinion, only the commits need to be squashed properly, and the bugfix should go into an own commit.

Let's ship this! :ship:  Thank you so much for your hard work on this, @Undef-a and for all the reviewing, @adriaandegroot!

PS: regarding translations: I think we should add tr() around all the strings eventually, and use template strings in javascript to fill in the variables (at least the QT version used in pmOS supports this, we should also check if it works with debian's QT). But of course, that's for another PR.

2021-02-21 18:46 UTC, ollieparanoid commented on modules/mobile/Config.cpp
> +    m_cmdMkfsRootBtrfs = getString( cfgMap, "cmdMkfsRootBtrfs", "mkfs.btrfs -L 'unknownOS_root'" );
That could work, but yes, out of scope for this PR.

To explain a bit why the full FS command can be set: distros may have specific options for the FS commands (for example in postmarketOS we have two ext4 options to ensure that it works with older downstream kernels too), or use different commands altogether (e.g. for btrfs, which needs to be wrapped in a script that also creates subvolumes and sets default ones).

2021-02-21 18:46 UTC, ollieparanoid commented on modules/mobile/Config.h
> +    bool m_installFromExternalToInternal = false;
I just read the code again where the variable gets used, and indeed, we must set this to false!

Otherwise it is uninitialized if the install target screen is skipped. Looks like it was only "false" by chance in my testing, and this went unnoticed in the proper postmarketOS installer images because we don't skip the dialog there (unless flashing to eMMC, which most people don't do).

Can you put this bugfix into a separate commit inside this PR?

2021-02-23 10:17 UTC, merged